// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const consumeUserToken = `-- name: ConsumeUserToken :one
UPDATE user_tokens
SET used_at = NOW()
WHERE token_hash = $1
  AND kind = $2
  AND used_at IS NULL
  AND expires_at > NOW()
RETURNING id, user_id, kind, token_hash, expires_at, used_at, created_at
`

type ConsumeUserTokenParams struct {
	TokenHash string
	Kind      TokenKind
}

func (q *Queries) ConsumeUserToken(ctx context.Context, arg ConsumeUserTokenParams) (UserToken, error) {
	row := q.db.QueryRowContext(ctx, consumeUserToken, arg.TokenHash, arg.Kind)
	var i UserToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createUserToken = `-- name: CreateUserToken :one
INSERT INTO user_tokens (
    user_id,
    kind,
    token_hash,
    expires_at
) VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id, user_id, kind, token_hash, expires_at, used_at, created_at
`

type CreateUserTokenParams struct {
	UserID    int64
	Kind      TokenKind
	TokenHash string
	ExpiresAt time.Time
}

func (q *Queries) CreateUserToken(ctx context.Context, arg CreateUserTokenParams) (UserToken, error) {
	row := q.db.QueryRowContext(ctx, createUserToken,
		arg.UserID,
		arg.Kind,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var i UserToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredUserTokens = `-- name: DeleteExpiredUserTokens :execrows
DELETE FROM user_tokens
WHERE expires_at < NOW()
    AND used_at IS NULL
`

func (q *Queries) DeleteExpiredUserTokens(ctx context.Context) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteExpiredUserTokens)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteUsedUserTokens = `-- name: DeleteUsedUserTokens :execrows
DELETE FROM user_tokens
WHERE used_at IS NOT NULL
`

func (q *Queries) DeleteUsedUserTokens(ctx context.Context) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteUsedUserTokens)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const expireUserTokens = `-- name: ExpireUserTokens :exec
UPDATE user_tokens
SET expires_at = NOW()
WHERE user_id = $1
  AND kind = $2
  AND used_at IS NULL
  AND expires_at > NOW()
`

type ExpireUserTokensParams struct {
	UserID int64
	Kind   TokenKind
}

func (q *Queries) ExpireUserTokens(ctx context.Context, arg ExpireUserTokensParams) error {
	_, err := q.db.ExecContext(ctx, expireUserTokens, arg.UserID, arg.Kind)
	return err
}

const getUserToken = `-- name: GetUserToken :one
SELECT id, user_id, kind, token_hash, expires_at, used_at, created_at
FROM user_tokens
WHERE token_hash = $1
  AND kind = $2
  AND used_at IS NULL
  AND expires_at > NOW()
`

type GetUserTokenParams struct {
	TokenHash string
	Kind      TokenKind
}

func (q *Queries) GetUserToken(ctx context.Context, arg GetUserTokenParams) (UserToken, error) {
	row := q.db.QueryRowContext(ctx, getUserToken, arg.TokenHash, arg.Kind)
	var i UserToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const setUserPasswordHash = `-- name: SetUserPasswordHash :one
UPDATE users
SET password_hash = $2
WHERE id = $1
RETURNING id, username, email, password_hash, email_verified_at, last_login_at, last_seen_at, is_active, disabled_reason, disabled_at, failed_login_count, locked_until, created_at, updated_at, auth_version, last_failed_login_at
`

type SetUserPasswordHashParams struct {
	ID           int64
	PasswordHash sql.NullString
}

func (q *Queries) SetUserPasswordHash(ctx context.Context, arg SetUserPasswordHashParams) (User, error) {
	row := q.db.QueryRowContext(ctx, setUserPasswordHash, arg.ID, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.LastLoginAt,
		&i.LastSeenAt,
		&i.IsActive,
		&i.DisabledReason,
		&i.DisabledAt,
		&i.FailedLoginCount,
		&i.LockedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AuthVersion,
		&i.LastFailedLoginAt,
	)
	return i, err
}

const useUserToken = `-- name: UseUserToken :exec
UPDATE user_tokens
SET used_at = NOW()
WHERE id = $1
`

func (q *Queries) UseUserToken(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, useUserToken, id)
	return err
}
