// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: mailer.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"base/internal/store/dbtype"
)

const deleteFailedEmailsBefore = `-- name: DeleteFailedEmailsBefore :execrows
DELETE FROM email_outbox
WHERE sent_at IS NULL
  AND last_error IS NOT NULL
  AND available_at < $1
`

func (q *Queries) DeleteFailedEmailsBefore(ctx context.Context, availableAt time.Time) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteFailedEmailsBefore, availableAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteSentEmailsBefore = `-- name: DeleteSentEmailsBefore :execrows
DELETE FROM email_outbox
WHERE sent_at IS NOT NULL
  AND sent_at < $1
`

func (q *Queries) DeleteSentEmailsBefore(ctx context.Context, sentAt sql.NullTime) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteSentEmailsBefore, sentAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const enqueueEmail = `-- name: EnqueueEmail :one
INSERT INTO email_outbox (
    template,
    recipient,
    subject,
    payload,
    available_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, template, recipient, subject, payload, available_at, sent_at, attempts, last_error, created_at, updated_at
`

type EnqueueEmailParams struct {
	Template    string
	Recipient   string
	Subject     string
	Payload     dbtype.RawMessage
	AvailableAt time.Time
}

func (q *Queries) EnqueueEmail(ctx context.Context, arg EnqueueEmailParams) (EmailOutbox, error) {
	row := q.db.QueryRowContext(ctx, enqueueEmail,
		arg.Template,
		arg.Recipient,
		arg.Subject,
		arg.Payload,
		arg.AvailableAt,
	)
	var i EmailOutbox
	err := row.Scan(
		&i.ID,
		&i.Template,
		&i.Recipient,
		&i.Subject,
		&i.Payload,
		&i.AvailableAt,
		&i.SentAt,
		&i.Attempts,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPendingEmails = `-- name: ListPendingEmails :many
SELECT id, template, recipient, subject, payload, available_at, sent_at, attempts, last_error, created_at, updated_at
FROM email_outbox
WHERE sent_at IS NULL
  AND available_at <= NOW()
ORDER BY available_at ASC
LIMIT $1
`

func (q *Queries) ListPendingEmails(ctx context.Context, limit int32) ([]EmailOutbox, error) {
	rows, err := q.db.QueryContext(ctx, listPendingEmails, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EmailOutbox
	for rows.Next() {
		var i EmailOutbox
		if err := rows.Scan(
			&i.ID,
			&i.Template,
			&i.Recipient,
			&i.Subject,
			&i.Payload,
			&i.AvailableAt,
			&i.SentAt,
			&i.Attempts,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markEmailFailed = `-- name: MarkEmailFailed :exec
UPDATE email_outbox
SET attempts = attempts + 1,
    last_error = $1,
    available_at = NOW() + ($2::int * INTERVAL '1 second')
WHERE id = $3
`

type MarkEmailFailedParams struct {
	LastError         sql.NullString
	RetryDelaySeconds int32
	ID                int64
}

func (q *Queries) MarkEmailFailed(ctx context.Context, arg MarkEmailFailedParams) error {
	_, err := q.db.ExecContext(ctx, markEmailFailed, arg.LastError, arg.RetryDelaySeconds, arg.ID)
	return err
}

const markEmailSent = `-- name: MarkEmailSent :exec
UPDATE email_outbox
SET sent_at = NOW()
WHERE id = $1
`

func (q *Queries) MarkEmailSent(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, markEmailSent, id)
	return err
}
