// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"

	"base/internal/store/dbtype"
	"github.com/google/uuid"
)

type TokenKind string

const (
	TokenKindPasswordReset     TokenKind = "password_reset"
	TokenKindEmailVerification TokenKind = "email_verification"
	TokenKindAccountRecovery   TokenKind = "account_recovery"
)

func (e *TokenKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TokenKind(s)
	case string:
		*e = TokenKind(s)
	default:
		return fmt.Errorf("unsupported scan type for TokenKind: %T", src)
	}
	return nil
}

type NullTokenKind struct {
	TokenKind TokenKind
	Valid     bool // Valid is true if TokenKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTokenKind) Scan(value interface{}) error {
	if value == nil {
		ns.TokenKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TokenKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTokenKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TokenKind), nil
}

type EmailOutbox struct {
	ID          int64
	Template    string
	Recipient   string
	Subject     string
	Payload     dbtype.RawMessage
	AvailableAt time.Time
	SentAt      sql.NullTime
	Attempts    int32
	LastError   sql.NullString
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type OauthAccount struct {
	ID                     int64
	UserID                 int64
	Provider               string
	ProviderUserID         string
	AccessTokenCiphertext  []byte
	RefreshTokenCiphertext []byte
	TokenExpiresAt         sql.NullTime
	CreatedAt              time.Time
	UpdatedAt              time.Time
}

type PasskeyCredential struct {
	ID                  int64
	UserID              int64
	CredentialID        []byte
	CredentialPublicKey []byte
	AttestationType     string
	Aaguid              uuid.NullUUID
	SignCount           int64
	CloneWarning        bool
	Transports          []string
	Name                sql.NullString
	CredentialData      dbtype.RawMessage
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

type Role struct {
	ID          int64
	Name        string
	Description sql.NullString
	CreatedAt   time.Time
}

type Session struct {
	Token  string
	Data   []byte
	Expiry time.Time
}

type TotpConfiguration struct {
	ID               int64
	UserID           int64
	SecretCiphertext []byte
	SecretNonce      []byte
	EnabledAt        sql.NullTime
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type User struct {
	ID                int64
	Username          string
	Email             string
	PasswordHash      sql.NullString
	EmailVerifiedAt   sql.NullTime
	LastLoginAt       sql.NullTime
	LastSeenAt        sql.NullTime
	IsActive          bool
	DisabledReason    sql.NullString
	DisabledAt        sql.NullTime
	FailedLoginCount  int32
	LockedUntil       sql.NullTime
	CreatedAt         time.Time
	UpdatedAt         time.Time
	AuthVersion       int64
	LastFailedLoginAt sql.NullTime
}

type UserRole struct {
	UserID    int64
	RoleID    int64
	CreatedAt time.Time
}

type UserToken struct {
	ID        int64
	UserID    int64
	Kind      TokenKind
	TokenHash string
	ExpiresAt time.Time
	UsedAt    sql.NullTime
	CreatedAt time.Time
}
