// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: oauth.sql

package sqlc

import (
	"context"
	"database/sql"
)

const getOAuthAccountByProviderIdentity = `-- name: GetOAuthAccountByProviderIdentity :one
SELECT id, user_id, provider, provider_user_id, access_token_ciphertext, refresh_token_ciphertext, token_expires_at, created_at, updated_at
FROM oauth_accounts
WHERE provider = $1
  AND provider_user_id = $2
`

type GetOAuthAccountByProviderIdentityParams struct {
	Provider       string
	ProviderUserID string
}

func (q *Queries) GetOAuthAccountByProviderIdentity(ctx context.Context, arg GetOAuthAccountByProviderIdentityParams) (OauthAccount, error) {
	row := q.db.QueryRowContext(ctx, getOAuthAccountByProviderIdentity, arg.Provider, arg.ProviderUserID)
	var i OauthAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.AccessTokenCiphertext,
		&i.RefreshTokenCiphertext,
		&i.TokenExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOAuthAccountByUserIDAndProvider = `-- name: GetOAuthAccountByUserIDAndProvider :one
SELECT id, user_id, provider, provider_user_id, access_token_ciphertext, refresh_token_ciphertext, token_expires_at, created_at, updated_at
FROM oauth_accounts
WHERE user_id = $1
  AND provider = $2
`

type GetOAuthAccountByUserIDAndProviderParams struct {
	UserID   int64
	Provider string
}

func (q *Queries) GetOAuthAccountByUserIDAndProvider(ctx context.Context, arg GetOAuthAccountByUserIDAndProviderParams) (OauthAccount, error) {
	row := q.db.QueryRowContext(ctx, getOAuthAccountByUserIDAndProvider, arg.UserID, arg.Provider)
	var i OauthAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.AccessTokenCiphertext,
		&i.RefreshTokenCiphertext,
		&i.TokenExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertOAuthAccount = `-- name: UpsertOAuthAccount :one
INSERT INTO oauth_accounts (
    user_id,
    provider,
    provider_user_id,
    access_token_ciphertext,
    refresh_token_ciphertext,
    token_expires_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
ON CONFLICT (provider, provider_user_id)
DO UPDATE SET
    user_id = EXCLUDED.user_id,
    access_token_ciphertext = EXCLUDED.access_token_ciphertext,
    refresh_token_ciphertext = EXCLUDED.refresh_token_ciphertext,
    token_expires_at = EXCLUDED.token_expires_at
RETURNING id, user_id, provider, provider_user_id, access_token_ciphertext, refresh_token_ciphertext, token_expires_at, created_at, updated_at
`

type UpsertOAuthAccountParams struct {
	UserID                 int64
	Provider               string
	ProviderUserID         string
	AccessTokenCiphertext  []byte
	RefreshTokenCiphertext []byte
	TokenExpiresAt         sql.NullTime
}

func (q *Queries) UpsertOAuthAccount(ctx context.Context, arg UpsertOAuthAccountParams) (OauthAccount, error) {
	row := q.db.QueryRowContext(ctx, upsertOAuthAccount,
		arg.UserID,
		arg.Provider,
		arg.ProviderUserID,
		arg.AccessTokenCiphertext,
		arg.RefreshTokenCiphertext,
		arg.TokenExpiresAt,
	)
	var i OauthAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.AccessTokenCiphertext,
		&i.RefreshTokenCiphertext,
		&i.TokenExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
