// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: passkeys.sql

package sqlc

import (
	"context"
	"database/sql"

	"base/internal/store/dbtype"
	"github.com/google/uuid"
	"github.com/lib/pq"
)

const createPasskeyCredential = `-- name: CreatePasskeyCredential :one
INSERT INTO passkey_credentials (
    user_id,
    credential_id,
    credential_public_key,
    attestation_type,
    aaguid,
    sign_count,
    clone_warning,
    transports,
    name,
    credential_data
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, user_id, credential_id, credential_public_key, attestation_type, aaguid, sign_count, clone_warning, transports, name, credential_data, created_at, updated_at
`

type CreatePasskeyCredentialParams struct {
	UserID              int64
	CredentialID        []byte
	CredentialPublicKey []byte
	AttestationType     string
	Aaguid              uuid.NullUUID
	SignCount           int64
	CloneWarning        bool
	Transports          []string
	Name                sql.NullString
	CredentialData      dbtype.RawMessage
}

func (q *Queries) CreatePasskeyCredential(ctx context.Context, arg CreatePasskeyCredentialParams) (PasskeyCredential, error) {
	row := q.db.QueryRowContext(ctx, createPasskeyCredential,
		arg.UserID,
		arg.CredentialID,
		arg.CredentialPublicKey,
		arg.AttestationType,
		arg.Aaguid,
		arg.SignCount,
		arg.CloneWarning,
		pq.Array(arg.Transports),
		arg.Name,
		arg.CredentialData,
	)
	var i PasskeyCredential
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CredentialID,
		&i.CredentialPublicKey,
		&i.AttestationType,
		&i.Aaguid,
		&i.SignCount,
		&i.CloneWarning,
		pq.Array(&i.Transports),
		&i.Name,
		&i.CredentialData,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePasskeyCredential = `-- name: DeletePasskeyCredential :execrows
DELETE FROM passkey_credentials
WHERE id = $1
  AND user_id = $2
`

type DeletePasskeyCredentialParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) DeletePasskeyCredential(ctx context.Context, arg DeletePasskeyCredentialParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deletePasskeyCredential, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listPasskeyCredentialsByUserID = `-- name: ListPasskeyCredentialsByUserID :many
SELECT id, user_id, credential_id, credential_public_key, attestation_type, aaguid, sign_count, clone_warning, transports, name, credential_data, created_at, updated_at
FROM passkey_credentials
WHERE user_id = $1
ORDER BY id ASC
`

func (q *Queries) ListPasskeyCredentialsByUserID(ctx context.Context, userID int64) ([]PasskeyCredential, error) {
	rows, err := q.db.QueryContext(ctx, listPasskeyCredentialsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PasskeyCredential
	for rows.Next() {
		var i PasskeyCredential
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CredentialID,
			&i.CredentialPublicKey,
			&i.AttestationType,
			&i.Aaguid,
			&i.SignCount,
			&i.CloneWarning,
			pq.Array(&i.Transports),
			&i.Name,
			&i.CredentialData,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePasskeyCredential = `-- name: UpdatePasskeyCredential :exec
UPDATE passkey_credentials
SET
    credential_public_key = $2,
    attestation_type = $3,
    aaguid = $4,
    sign_count = $5,
    clone_warning = $6,
    transports = $7,
    name = COALESCE($8, name),
    credential_data = $9
WHERE credential_id = $1
`

type UpdatePasskeyCredentialParams struct {
	CredentialID        []byte
	CredentialPublicKey []byte
	AttestationType     string
	Aaguid              uuid.NullUUID
	SignCount           int64
	CloneWarning        bool
	Transports          []string
	Name                sql.NullString
	CredentialData      dbtype.RawMessage
}

func (q *Queries) UpdatePasskeyCredential(ctx context.Context, arg UpdatePasskeyCredentialParams) error {
	_, err := q.db.ExecContext(ctx, updatePasskeyCredential,
		arg.CredentialID,
		arg.CredentialPublicKey,
		arg.AttestationType,
		arg.Aaguid,
		arg.SignCount,
		arg.CloneWarning,
		pq.Array(arg.Transports),
		arg.Name,
		arg.CredentialData,
	)
	return err
}
