// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: totp.sql

package sqlc

import (
	"context"
	"database/sql"
)

const deleteTotpConfigurationByUserID = `-- name: DeleteTotpConfigurationByUserID :exec
DELETE FROM totp_configurations
WHERE user_id = $1
`

func (q *Queries) DeleteTotpConfigurationByUserID(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, deleteTotpConfigurationByUserID, userID)
	return err
}

const enableTotpConfiguration = `-- name: EnableTotpConfiguration :exec
UPDATE totp_configurations
SET enabled_at = NOW()
WHERE user_id = $1
`

func (q *Queries) EnableTotpConfiguration(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, enableTotpConfiguration, userID)
	return err
}

const getTotpConfigurationByUserID = `-- name: GetTotpConfigurationByUserID :one
SELECT id, user_id, secret_ciphertext, secret_nonce, enabled_at, created_at, updated_at
FROM totp_configurations
WHERE user_id = $1
`

func (q *Queries) GetTotpConfigurationByUserID(ctx context.Context, userID int64) (TotpConfiguration, error) {
	row := q.db.QueryRowContext(ctx, getTotpConfigurationByUserID, userID)
	var i TotpConfiguration
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SecretCiphertext,
		&i.SecretNonce,
		&i.EnabledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertTotpConfiguration = `-- name: UpsertTotpConfiguration :one
INSERT INTO totp_configurations (
    user_id,
    secret_ciphertext,
    secret_nonce,
    enabled_at
) VALUES (
    $1,
    $2,
    $3,
    $4
)
ON CONFLICT (user_id)
DO UPDATE SET
    secret_ciphertext = EXCLUDED.secret_ciphertext,
    secret_nonce = EXCLUDED.secret_nonce,
    enabled_at = EXCLUDED.enabled_at
RETURNING id, user_id, secret_ciphertext, secret_nonce, enabled_at, created_at, updated_at
`

type UpsertTotpConfigurationParams struct {
	UserID           int64
	SecretCiphertext []byte
	SecretNonce      []byte
	EnabledAt        sql.NullTime
}

func (q *Queries) UpsertTotpConfiguration(ctx context.Context, arg UpsertTotpConfigurationParams) (TotpConfiguration, error) {
	row := q.db.QueryRowContext(ctx, upsertTotpConfiguration,
		arg.UserID,
		arg.SecretCiphertext,
		arg.SecretNonce,
		arg.EnabledAt,
	)
	var i TotpConfiguration
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SecretCiphertext,
		&i.SecretNonce,
		&i.EnabledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
