// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    username,
    email
) VALUES (
    $1,
    $2
)
RETURNING id, username, email, password_hash, email_verified_at, last_login_at, last_seen_at, is_active, disabled_reason, disabled_at, failed_login_count, locked_until, created_at, updated_at, auth_version, last_failed_login_at
`

type CreateUserParams struct {
	Username string
	Email    string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Username, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.LastLoginAt,
		&i.LastSeenAt,
		&i.IsActive,
		&i.DisabledReason,
		&i.DisabledAt,
		&i.FailedLoginCount,
		&i.LockedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AuthVersion,
		&i.LastFailedLoginAt,
	)
	return i, err
}

const disableInactiveUsers = `-- name: DisableInactiveUsers :many
UPDATE users
SET is_active = FALSE,
    disabled_reason = 'inactivity',
    disabled_at = NOW()
WHERE is_active = TRUE
  AND COALESCE(last_login_at, created_at) < $1
RETURNING id, username, email, password_hash, email_verified_at, last_login_at, last_seen_at, is_active, disabled_reason, disabled_at, failed_login_count, locked_until, created_at, updated_at, auth_version, last_failed_login_at
`

func (q *Queries) DisableInactiveUsers(ctx context.Context, lastLoginAt sql.NullTime) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, disableInactiveUsers, lastLoginAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.PasswordHash,
			&i.EmailVerifiedAt,
			&i.LastLoginAt,
			&i.LastSeenAt,
			&i.IsActive,
			&i.DisabledReason,
			&i.DisabledAt,
			&i.FailedLoginCount,
			&i.LockedUntil,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthVersion,
			&i.LastFailedLoginAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, password_hash, email_verified_at, last_login_at, last_seen_at, is_active, disabled_reason, disabled_at, failed_login_count, locked_until, created_at, updated_at, auth_version, last_failed_login_at
FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.LastLoginAt,
		&i.LastSeenAt,
		&i.IsActive,
		&i.DisabledReason,
		&i.DisabledAt,
		&i.FailedLoginCount,
		&i.LockedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AuthVersion,
		&i.LastFailedLoginAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, email, password_hash, email_verified_at, last_login_at, last_seen_at, is_active, disabled_reason, disabled_at, failed_login_count, locked_until, created_at, updated_at, auth_version, last_failed_login_at
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.LastLoginAt,
		&i.LastSeenAt,
		&i.IsActive,
		&i.DisabledReason,
		&i.DisabledAt,
		&i.FailedLoginCount,
		&i.LockedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AuthVersion,
		&i.LastFailedLoginAt,
	)
	return i, err
}

const getUserWithPasswordByEmail = `-- name: GetUserWithPasswordByEmail :one
SELECT id, username, email, password_hash, email_verified_at, last_login_at, last_seen_at, is_active, disabled_reason, disabled_at, failed_login_count, locked_until, created_at, updated_at, auth_version, last_failed_login_at
FROM users
WHERE email = $1
  AND password_hash IS NOT NULL
`

func (q *Queries) GetUserWithPasswordByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserWithPasswordByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.LastLoginAt,
		&i.LastSeenAt,
		&i.IsActive,
		&i.DisabledReason,
		&i.DisabledAt,
		&i.FailedLoginCount,
		&i.LockedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AuthVersion,
		&i.LastFailedLoginAt,
	)
	return i, err
}

const incrementUserAuthVersion = `-- name: IncrementUserAuthVersion :one
UPDATE users
SET auth_version = auth_version + 1
WHERE id = $1
RETURNING auth_version
`

func (q *Queries) IncrementUserAuthVersion(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, incrementUserAuthVersion, id)
	var auth_version int64
	err := row.Scan(&auth_version)
	return auth_version, err
}

const lockUserUntil = `-- name: LockUserUntil :exec
UPDATE users
SET locked_until = $2,
    disabled_reason = $3
WHERE id = $1
`

type LockUserUntilParams struct {
	ID             int64
	LockedUntil    sql.NullTime
	DisabledReason sql.NullString
}

func (q *Queries) LockUserUntil(ctx context.Context, arg LockUserUntilParams) error {
	_, err := q.db.ExecContext(ctx, lockUserUntil, arg.ID, arg.LockedUntil, arg.DisabledReason)
	return err
}

const markUserEmailVerified = `-- name: MarkUserEmailVerified :exec
UPDATE users
SET email_verified_at = NOW()
WHERE id = $1
`

func (q *Queries) MarkUserEmailVerified(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, markUserEmailVerified, id)
	return err
}

const recordFailedLogin = `-- name: RecordFailedLogin :one
UPDATE users
SET failed_login_count = CASE
		WHEN last_failed_login_at IS NULL
		  OR last_failed_login_at < NOW() - ($1::bigint * INTERVAL '1 second')
        THEN 1
        ELSE failed_login_count + 1
    END,
    last_failed_login_at = NOW()
WHERE id = $2
RETURNING id, username, email, password_hash, email_verified_at, last_login_at, last_seen_at, is_active, disabled_reason, disabled_at, failed_login_count, locked_until, created_at, updated_at, auth_version, last_failed_login_at
`

type RecordFailedLoginParams struct {
	WindowSeconds int64
	ID            int64
}

func (q *Queries) RecordFailedLogin(ctx context.Context, arg RecordFailedLoginParams) (User, error) {
	row := q.db.QueryRowContext(ctx, recordFailedLogin, arg.WindowSeconds, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.LastLoginAt,
		&i.LastSeenAt,
		&i.IsActive,
		&i.DisabledReason,
		&i.DisabledAt,
		&i.FailedLoginCount,
		&i.LockedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AuthVersion,
		&i.LastFailedLoginAt,
	)
	return i, err
}

const resetLoginFailures = `-- name: ResetLoginFailures :exec
UPDATE users
SET failed_login_count = 0,
    last_failed_login_at = NULL,
    locked_until = NULL,
    disabled_reason = CASE
        WHEN disabled_reason = 'failed_login_attempts' THEN NULL
        ELSE disabled_reason
    END
WHERE id = $1
`

func (q *Queries) ResetLoginFailures(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, resetLoginFailures, id)
	return err
}

const restoreUserAccess = `-- name: RestoreUserAccess :exec
UPDATE users
SET is_active = TRUE,
    email_verified_at = COALESCE(email_verified_at, NOW()),
    failed_login_count = 0,
    last_failed_login_at = NULL,
    locked_until = NULL,
    disabled_reason = NULL,
    disabled_at = NULL
WHERE id = $1
`

func (q *Queries) RestoreUserAccess(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, restoreUserAccess, id)
	return err
}

const touchUserSeen = `-- name: TouchUserSeen :exec
UPDATE users
SET last_seen_at = NOW()
WHERE id = $1
`

func (q *Queries) TouchUserSeen(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, touchUserSeen, id)
	return err
}

const updateUserLastLogin = `-- name: UpdateUserLastLogin :exec
UPDATE users
SET last_login_at = NOW(),
    last_seen_at = NOW(),
    failed_login_count = 0,
    last_failed_login_at = NULL,
    locked_until = NULL,
    disabled_reason = CASE
        WHEN disabled_reason = 'failed_login_attempts' THEN NULL
        ELSE disabled_reason
    END
WHERE id = $1
`

func (q *Queries) UpdateUserLastLogin(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, updateUserLastLogin, id)
	return err
}
